name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step to set up Java (if not already set up)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'GraalVM'

      # Step to run tests and generate code coverage report using JaCoCo
      - name: 'Run tests with coverage'
        run: mvn clean test jacoco:report

      # Step to run Qodana scan
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
