name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: 'Save Qodana results as Markdown'
        run: |
          echo "## Qodana Report" > qodana-summary.md
          if [ -f qodana.sarif ]; then
            cat qodana.sarif | jq -r '.runs[0].results[] | "- \(.message.text): \(.locations[0].physicalLocation.artifactLocation.uri) (line \(.locations[0].physicalLocation.region.startLine))"' >> qodana-summary.md
          fi

      - name: 'Update README with Qodana summary'
        run: |
          sed -i '/## Qodana Report/,$d' README.md
          cat qodana-summary.md >> README.md
        if: success()

      - name: 'Commit updated README'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md qodana-summary.md
          git commit -m "Update README with latest Qodana results"
          git push
        if: success()
